### ISSUE TITLE
Plugin failed to load Gedit 10

### ISSUE THREAD

**Issue by raddad555** [jcca/go-gedit3-plugin#4]
Followed the instruction , i had to create the folder structure. it does show up when going tp preferances but will not load.

**Comment by jcca** [comment]
solved

**Comment by jcca** [comment]
Thanks for report issue.

**Comment by raddad555** [comment]
Thanks I will give it a try

**Comment by raddad555** [comment]
Juan I just tried it again but still fails

 

Warren

**Comment by jcca** [comment]
What is the error? 
it work for gedit 3.16.2

**Comment by raddad555** [comment]
Unfortunately not throwing any error other than failed to load. Sorry to take so long getting back to you been working on a couple projects. I been using sublime text 2 but would like to try gedit with your lib looks very kool. Thanks for taking the time.
